#!/usr/bin/env bash
docker run --name demobot -e DEMOBOT_ACCESS_TOKEN=$DEMOBOT_ACCESS_TOKEN -e DEMOBOT_EMAIL=$DEMOBOT_EMAIL -e DEMOBOT_NAME="$DEMOBOT_NAME" -e PTV_API_USER=$PTV_API_USER -e PTV_API_KEY=$PTV_API_KEY -d demobot
